language: node_js
node_js:
  - '11'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - .travis/before_script

script:
  - yarn build

after_success:
  - .travis/after_success
