language: node_js
node_js:
  - '11'

env:
  matrix:
    - SCRIPT=lint
    - SCRIPT=build
  global:
    - TZ=Asia/Tokyo

cache:
  directories:
    - node_modules

before_install:
  - source .travis/before_install

before_script:
  - source .travis/before_script

script:
  - source .travis/$SCRIPT

after_success:
  - source .travis/after_success
