#!/usr/bin/env bash

if [[ "$TRAVIS_BRANCH" = 'master' ]] && [[ "$TRAVIS_PULL_REQUEST" = 'false' ]]; then
    echo 'Cleaning...'
    ssh deploy rm -rf /srv/http/vhosts/chitoku.jp/historia/*
    echo 'Cleaned!'

    echo 'Uploading...'
    rsync -rz public/ deploy:/srv/http/vhosts/chitoku.jp/historia
    echo 'Uploaded!'
fi
