#!/usr/bin/env bash

if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    echo 'Uploading...'
    rsync public/ deploy:/srv/http/vhosts/chitoku.jp/historia
    echo 'Uploaded!'
fi
