#!/usr/bin/env bash

# Install the latest version of yarn
# See also: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-a-specific-yarn-version
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
export PATH=$HOME/.yarn/bin:$PATH

# Install full-icu
# See also: https://github.com/nodejs/help/issues/832
yarn global add full-icu
export NODE_ICU_DATA=$(node-full-icu-path)

# Install reviewdog
mkdir -p ~/.bin
curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | bash -s -- -b ~/.bin
export PATH=~/.bin/:$PATH
