#!/usr/bin/env bash

# Install the latest version of yarn
# See also: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-a-specific-yarn-version
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
export PATH="$HOME/.yarn/bin:$PATH"

if [[ "$SCRIPT" = 'build' ]]; then
    # Install full-icu
    # See also: https://github.com/nodejs/help/issues/832
    yarn global add full-icu
    export NODE_ICU_DATA=$(node-full-icu-path)
elif [[ "$SCRIPT" = 'lint' ]]; then
    # Install reviewdog
    mkdir -p ~/.bin
    curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | bash -s -- -b ~/.bin
    export PATH="~/.bin/:$PATH"
fi
