#!/usr/bin/env bash

{ yarn --silent lint:js && yarn --silent lint:ts; } | reviewdog -f=eslint -diff='git diff master'
{ yarn --silent lint:css && yarn --silent lint:styled; } | reviewdog -f=stylelint -diff='git diff master'
