name: CI Workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: Set up .env
        run: cp .env{.example,}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          target: build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: chitoku-k/chitoku.jp:build
          build-args: |
            CI
      - name: Run eslint
        if: ${{ always() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cwd=$(docker run --rm chitoku-k/chitoku.jp:build pwd)
          docker run --rm chitoku-k/chitoku.jp:build yarn lint:js | sed "s!$cwd/!!g" | reviewdog -f=eslint -reporter=github-pr-annotations -fail-on-error -tee
      - name: Run stylelint
        if: ${{ always() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm chitoku-k/chitoku.jp:build yarn lint:css 2>&1 | reviewdog -f=stylelint -reporter=github-pr-annotations -fail-on-error -tee
