name: CI Workflow
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up .env
        run: cp .env{.example,}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build (dependencies)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: dependencies
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build (cache)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: cache
          cache-from: type=gha
          cache-to: type=gha
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
