name: CI Workflow
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Extract .env
        run: echo "$ENVFILE" > .env
        env:
          ENVFILE: ${{ secrets.ENVFILE }}
      - name: Log into Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build .
