name: CI Workflow
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up .env
        run: cp .env{.example,}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Buildx
        uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-
      - name: Cache .cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: cache-${{ github.sha }}
          restore-keys: cache-
      - name: Cache public
        uses: actions/cache@v2
        with:
          path: public
          key: public-${{ github.sha }}
          restore-keys: public-
      - name: Build (dependencies)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: dependencies
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/buildx-cache.new
      - name: Build (cache)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: cache
          cache-from: type=local,src=/tmp/buildx-cache
          outputs: type=local,dest=/tmp/buildx-result
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
      - name: Move cache
        run: |
          rm -rf /tmp/buildx-cache
          mv /tmp/buildx-cache{.new,}
          rm -rf .cache public
          mv /tmp/buildx-result/usr/src/.cache .
          mv /tmp/buildx-result/usr/src/public .
