name: CI Workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up .env
        run: cp .env{.example,}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          target: build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: chitoku-k/chitoku.jp:build
          build-args: |
            CI
      - name: Lint
        run: |
          docker run --rm chitoku-k/chitoku.jp:build yarn lint:js --format=json --output-file=eslint_report.json
          docker run --rm chitoku-k/chitoku.jp:build yarn lint:css
      - name: Annotate eslint results
        if: ${{ always() }}
        uses: ataylorme/eslint-annotate-action@v3
        with:
          only-pr-files: false
